### ISSUE TITLE
TypeError: 'NoneType' object is not callable in recurrence_network.py

### ISSUE THREAD

**Issue by vinayakumarr** [pik-copan/pyunicorn#105]
I have tried to run the recurrence_network.py. The program works but it shows an error in the below line

`print "Recurrence rate:", rp.recurrence_rate()`

The detailed error is attached below

Recurrence rate:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-af21a0d16557> in <module>()
      1 #  Calculate and print the recurrence rate
----> 2 print "Recurrence rate:", rp.recurrence_rate(10)

TypeError: 'NoneType' object is not callable

**Comment by jkroenke** [comment]
This bug could not be reproduced and was probably solved in the migration process from python 2 to python 3.
