### ISSUE TITLE
Error when I import pyunicorn

### ISSUE THREAD

**Issue by manmeet3591** [pik-copan/pyunicorn#109]
I am getting the following error. 

>>> import pyunicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyunicorn/__init__.py", line 35, in <module>
    from .core import *
  File "pyunicorn/core/__init__.py", line 35, in <module>
    from .network import Network, NetworkError, nz_coords, cached_const
  File "pyunicorn/core/network.py", line 44, in <module>
    from pyunicorn.core._ext.numerics import _local_cliquishness_4thorder, \
ImportError: No module named numerics

**Comment by jdonges** [comment]
It seems like you have not compiled the cython extensions contained in the numerics module correctly. The easiest way to install pyunicorn properly is to use „pip install pyunicorn“, where the precompiled extensions are already included.

**Comment by manmeet3591** [comment]
Thanks. It worked. 

I was trying to do pip install previously as well, but some dependency issues were coming up that time maybe. This time it works

**Comment by zackgow** [comment]
I'm also getting a very similar issue. A fresh `pip install pyunicorn`, installing from the github repo, or installing the most stable release does not work.

```
----> 1 import pyunicorn

~/pyunicorn-0.5.1/pyunicorn/__init__.py in <module>()
     33 
     34 from .utils import mpi
---> 35 from .core import *
     36 
     37 

~/pyunicorn-0.5.1/pyunicorn/core/__init__.py in <module>()
     33 #
     34 
---> 35 from .network import Network, NetworkError, nz_coords, cached_const
     36 from .geo_network import GeoNetwork
     37 from .grid import Grid

~/pyunicorn-0.5.1/pyunicorn/core/network.py in <module>()
     41 from ..utils import mpi             # parallelized computations
     42 
---> 43 from ._ext.numerics import _local_cliquishness_4thorder, \
     44     _local_cliquishness_5thorder, _cy_mpi_nsi_newman_betweenness, \
     45     _cy_mpi_newman_betweenness, _nsi_betweenness, _higher_order_transitivity4,\
ModuleNotFoundError: No module named 'pyunicorn.core._ext.numerics'
```

Any tips?
