### ISSUE TITLE
Use basemap instead of PyNgl for map plotting

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#11]
Remove dependency on PyNgl and use basemap instead for map plotting class MapPlots or equivalent.

---

Originally reported by: Jonathan Donges
Originally created on: 2013-03-14

**Comment by ntfrgl** [comment]
I am working on a new mapplots class already. Functions will be the same as for now, but I am thinking of working on a whole plotting module that supports further options.

----------------------------------------
Original comment by: Marc Wiedermann
Original comment on: 2013-03-18

**Comment by ntfrgl** [comment]
[`Ngl.contour_map()`](http://www.pyngl.ucar.edu/Functions/Ngl.contour_map.shtml) -> [`Basemap.contour()`](http://matplotlib.org/basemap/api/basemap_api.html#mpl_toolkits.basemap.Basemap.contour) in `pygeonetwork/map_plots.py`

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-05-02

**Comment by ntfrgl** [comment]
Makes perfect sense. If basemap can be employed in MapPlots class without too much effort we should do it. But not high priority.


----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-05-02

**Comment by ntfrgl** [comment]
We could do this before the next release, thus removing another dependency.

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-10-15

**Comment by zugnachpankow** [comment]
#174 Introduced cartopy (Basemap is deprecated in favor of the [Cartopy project](http://scitools.org.uk/cartopy/)) for MapPlots class.
