### ISSUE TITLE
dok_matrix no longer allows update

### ISSUE THREAD

**Issue by jkroenke** [pik-copan/pyunicorn#115]
In the file network.py in the _mpi_nsi_arenas_betweenness function the line 3712:
```
sp_Pi.update(zip(update_keys, update_vals))
```
raises a NotImplementedError because dok_matrix no longer allows update (See this: https://github.com/scipy/scipy/issues/8338)

**Comment by ntfrgl** [comment]
I would use fancy indexing assignment, as suggested in the issue. That should be a one-line change.
