### ISSUE TITLE
BUG: Latex / PDF documentation shows old version number after compile

### ISSUE THREAD

**Issue by jdonges** [pik-copan/pyunicorn#121]
The version number of pyunicorn indicated in the Latex / PDF documentation after compile is outdated. Need to fix this and check where the version number is drawn from.

**Comment by jdonges** [comment]
Same issue for parts of the html documentation!

**Comment by jkroenke** [comment]
I compiled it and it seems correct. Where exactly are the wrong version numbers?

**Comment by jdonges** [comment]
I compiled it using Boyan’s publish script and, e.g., the headline page in the doc on API doc shows the wrong version number (still 0.5.2).

**Comment by jkroenke** [comment]
When I compile it by typing 'make latexpdf' the version number is correct. How is the documentation compiled in the publish script?

**Comment by jdonges** [comment]
Looks like I needed to run the publish script twice for it to update the version number in both PDF and html docs.
