### ISSUE TITLE
Repeatedly calling core.network.Network.interregional_betweenness gives wrong results

### ISSUE THREAD

**Issue by jkroenke** [pik-copan/pyunicorn#124]
When a network is initialized and interregional_betweenness is called
```python
net = Network.SmallTestNetwork()
net.interregional_betweenness(sources=[2], targets=[3, 5])
```
the result
```python
array([1., 1., 0., 0., 1., 0.])
```
is correct for the first calculation. However, if interregional_betweenness is called a second time with different source and/or target nodes
```python
net.interregional_betweenness(sources=range(0, 6), targets=range(0, 6))
```
the result is still the same. For a newly initialized network it is different:
```python
array([9., 3., 0., 2., 6., 0.])
```

**Comment by jkroenke** [comment]
The problem occurs in core.network.Network.nsi_interregional_betweenness, too. As both call nsi_betweenness, I suspect the problem comes from there.

**Comment by ntfrgl** [comment]
`@cached_const` is wrong here. It should be either deleted or replaced with `@cached_var`. In the latter case, the decorator would need to be patched to handle `sources=..., targets=...` instead of `key=...`.

**Comment by ntfrgl** [comment]
We should probably rather use
