### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by guist** [pik-copan/pyunicorn#138]
Hello,

I am working with WSL (Windows Sub-System for Linux), Ubuntu 18.04 and I am trying to install pyunicorn with pip, but it does not work.

First, I tried:
`pip install pyunicorn`
and I got the following error:
`Building wheel for pyunicorn (setup.py) ... error`

Then I tried:
`sudo -H pip install pyunicorn`
and the previous error disappeared, but I got a new one:
```
Collecting pyunicorn
  Using cached https://files.pythonhosted.org/packages/97/4a/2b146e06088bffa6249ebc360b16d7c6045401b5d60f1817a68dac40fbda/pyunicorn-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i8lbjb/pyunicorn/setup.py", line 43
        f'pyunicorn.{pkg}._ext.numerics',
                                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i8lbjb/pyunicorn/
```

Could you please tell me how to deal with this error?

Thanks!
Guillaume

**Comment by tburleyinfo** [comment]
I had this problem. 

I tried installing with pip3. and got the same error. then I ran 
`pip3 install Cython`

and then 

`pip3 install pyunicorn`

It worked for me.

**Comment by renzocom** [comment]
`pip install Cython`

solved for me also!

**Comment by renzocom** [comment]
`pip install Cython` solved for me also!

I would recommend Cython to be added as required dependency as many people seem to be getting the same error:

https://github.com/pik-copan/pyunicorn/issues/122
https://github.com/pik-copan/pyunicorn/issues/134

**Comment by bovedder** [comment]
same issue, also on ubuntu 20.04. Also it is solved by doing:

pip3 install Cython

and then

pip3 install pyunicorn

**Comment by SethGo** [comment]
pip3 install Cython 
Worked for me too. Should be in requirements.

**Comment by thejuc** [comment]
Still having trouble. Getting the following: 
`  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyunicorn
  Running setup.py clean for pyunicorn
Failed to build pyunicorn
Installing collected packages: pyunicorn
    Running setup.py install for pyunicorn ... error
    ERROR: Command errored out with exit status 1:`
