### ISSUE TITLE
Core Dump when calculating Supremum Distance Matrix

### ISSUE THREAD

**Issue by madarax64** [pik-copan/pyunicorn#141]
Hello,
I was using PyUnicorn for RQA on some dataset. However, I get the following error on some samples, which terminates my program with a core dump:

```
Calculating the supremum distance matrix...
corrupted size vs. prev_size
Aborted (core dumped)
```
I'm running on Python 3.6 on Ubuntu 18.04 via WSL. 
Any help with this would be really really appreciated.

Thanks in advance

**Comment by ntfrgl** [comment]
@fkuehlein, this might be related to #128.

**Comment by fkuehlein** [comment]
Agreed. `RecurrencePlot` and `CrossRecurrencePlot` are the only classes that calculate the supremum distance matrix, which was fixed in the above commits.

This issue can therefore be closed.
