### ISSUE TITLE
Import fails in Kaggle notebook (Python 3.7.6)

### ISSUE THREAD

**Issue by AScholan** [pik-copan/pyunicorn#147]
### Environment

* Kaggle notebook Python 3.7.6

### What was I trying to do?

* Import and use the PyUnicorn library

### What happened?

1. pip install works as expected
2. import fails with exception: getopt.GetoptError: option -f not recognized

### To repeat?
See https://www.kaggle.com/andrewscholan/pyunicorn-import-issue

1. Create notebook in Kaggle, select Python.
2. Enter code cell: 

> !pip install pyunicorn

3. Enter code cell:

> from pyunicorn.timeseries import RecurrencePlot

Any help would be appreciated.
Thank you,
Andrew.

**Comment by haricash** [comment]
Any updates on this issue? I am facing a (possibly) related issue when trying to open `pyunicorn` after installing it on a Colab notebook using `!pip install pyunicorn` - I get a setup.py missing error

**Comment by ntfrgl** [comment]
Thank you for reporting this issue, and please accept our apologies for our delay in providing a rigorous solution. This set of problems should be fully resolved with the commit linked above, which will be reflected in an upcoming new release including official wheels. I'm tentatively closing this ticket, but please let us know in case you have any trouble installing `pyunicorn` from the current `master` branch, in which case we will attempt to find a solution as quickly as possible.

Cython is now declared as a build dependency, which means that your Python package manager (e.g., `pip`) is responsible for automatically providing the Cython compiler without any user intervention. After the package installation process is completed, Cython is **not** required as a runtime dependency. The version information is now retrieved via `importlib.metadata` from the Python standard library.
