### ISSUE TITLE
`setup.py` missing in pip install

### ISSUE THREAD

**Issue by haricash** [pik-copan/pyunicorn#158]
Hello! I am trying out pyunicorn on Google Colab and I ran into the following error when I tried `!pip install` followed by `import pyunicorn` : 

`ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-15-270ebaac4cb0>](https://localhost:8080/#) in <module>()
      1 get_ipython().system('pip3 install pyunicorn')
----> 2 import pyunicorn

[/usr/local/lib/python3.7/dist-packages/pyunicorn/__init__.py](https://localhost:8080/#) in <module>()
     41 import sys
     42 
---> 43 from setup import __version__
     44 
     45 from .utils import mpi

ModuleNotFoundError: No module named 'setup'` 

It would be great if you could help me out in this issue!

**Comment by ntfrgl** [comment]
Thank you for reporting this issue, and please accept our apologies for our delay in providing a rigorous solution. This set of problems should be fully resolved with the commit linked above, which will be reflected in an upcoming new release including official wheels. I'm tentatively closing this ticket, but please let us know in case you have any trouble installing `pyunicorn` from the current `master` branch, in which case we will attempt to find a solution as quickly as possible.

Cython is now declared as a build dependency, which means that your Python package manager (e.g., `pip`) is responsible for automatically providing the Cython compiler without any user intervention. After the package installation process is completed, Cython is **not** required as a runtime dependency. The version information is now retrieved via `importlib.metadata` from the Python standard library.

**Comment by haricash** [comment]
Thank you for your response. I managed to install it locally on my system
after some fooling around.

I wanted to quickly add a follow up- there is a segfault in the mutual
information calculation function. Hopefully that is getting fixed too!

Also, when can we expect the next release? I'm using it for a project with
a deadline, and hopefully it comes up within the next few days.

**Comment by ntfrgl** [comment]
The release date is not up to me, but I wouldn't bet on it happening within a few days.

Please try to run your code with the current `master`, and in case the segmentation fault persists, open a separate issue with a reproducible example.

**Comment by haricash** [comment]
Will do, thanks!

**Comment by haricash** [comment]
Hello,
Is there an alternative to using PyNGL being planned in the next release?
PyNGL has gone into maintenance mode and a lot of plotting functionalities
are not currently being supported.
