### ISSUE TITLE
cannot import GeoGrid

### ISSUE THREAD

**Issue by rimajj** [pik-copan/pyunicorn#169]
When trying to import GeoGrid class my IDE tells me "Cannot find reference 'geo_grid' in '__init__.py | __init__.py' ".
I tried to import like this:
from pyunicorn.core.geo_grid import GeoGrid

pyunicorn version: 0.6.1

How can I fix this?

Best regards

**Comment by zugnachpankow** [comment]
Hey @rimajj,

does this only happen with the GeoGrid class? In a quick check on my system the import worked fine.

**Comment by rimajj** [comment]
Hi @zugnachpankow,
Thanks for your quick answer.
Although I am not quite sure what is going on with my IDE, I think this issue can be closed.
I tried all Classes imported in core.__init__.py and this message only occurred with GeoGrid and SpatialNetwork. However, despite of telling me that GeoGrid is an unresolved reference, I am able to use the class in my program.
Even stranger, in a different program using the same env and pyunicorn version, GeoGrid can be imported without the "Cannot find reference 'geo_grid' in 'init.py | init.py' " message.
