### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by drkousek** [pik-copan/pyunicorn#171]
Hey!
I was not quite sucesfull in installing pyunicorn. After installation of build tools, i tried install it, but unsucesffully. It says some weird things and I am not able to install it.
Python version 3. 9. 9
No idea, why is that. Could you help me?
![image](https://user-images.githubusercontent.com/26819551/212547242-27c9d73b-3ab1-48ae-aac1-af3f6916e0e0.png)

**Comment by zugnachpankow** [comment]
Hey, 

unfortunately we still face problems with windows installations. 

Do you have cython installed?

**Comment by drkousek** [comment]
Yes, I have.

**Comment by ntfrgl** [comment]
I am closing this issue, since it is a duplicate of #160 with the same error messages and the same causes.

@drkousek, could you please retry with the most recent `master` branch, and report back in the referenced issue? Thank you!
