### ISSUE TITLE
Plot a recurrence network (Question) 

### ISSUE THREAD

**Issue by Xorrn** [pik-copan/pyunicorn#181]
Hi, I'd like to plot a recurrence network generated with your package (for example the RN in your tutorial). Is there some way to do this? I couldn't find anything about this in the documentation. Thanks!

**Comment by fkuehlein** [comment]
Hi @Xorrn,

sorry for the delayed response. You can simply plot a `pyunicorn.timeseries.RecurrenceNetwork` using [`igraph`](https://python.igraph.org/en/stable/) (which you should have installed already as it is a dependency of `pyunicorn`). To use it's plotting functionality, you'll have to install [`pycairo`](https://pycairo.readthedocs.io/en/latest/) as well.

For a given `time_series`, just generate an `igraph` object from the `RecurrenceNetwork`'s adjacency matrix and then plot it. Here's a simple example:

```python
import igraph
from pyunicorn.timeseries import RecurrenceNetwork

rn = RecurrenceNetwork(time_series, threshold_std=EPS_std)

A = rn.adjacency # get adjacency matrix
n = np.linspace(0, A.shape[0], A.shape[0]+1) # create node numbering

g = igraph.Graph.Adjacency(A.astype(bool).tolist()) # igraph needs A to be a list of booleans 
g.vs['label'] = n # add labels
igraph.plot(g) # plot the network
```

Hope this helps!
