### ISSUE TITLE
BUG: segfault when calling `CouplingAnalysis.mutual_information()` and `CouplingAnalysis.information_transfer()`

### ISSUE THREAD

**Issue by fkuehlein** [pik-copan/pyunicorn#187]
Might be a similar problem as in issue #128, pointing to an indexation error in an underlying C function.

Discovered this behaviour when running the test suite. The corresponding tests [`test_mutual_information`](https://github.com/pik-copan/pyunicorn/blob/master/tests/test_funcnet/test_coupling_analysis.py#L86) and [`test_information_transfer`](https://github.com/pik-copan/pyunicorn/blob/master/tests/test_funcnet/test_coupling_analysis.py#L102) currently remain the only ones failing.

[`coupling_analysis.mutual_information()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/coupling_analysis.py#L230) and [`coupling_analysis.information_transfer()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/coupling_analysis.py#L419) are the only methods in class calling [`coupling_analysis.get_nearest_neighbors()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/coupling_analysis.py#L636), which relies on [`funcnet._ext.numerics._get_nearest_neighbors()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/_ext/numerics.pyx#L115) and the C function [`_get_nearest_neighbors_fast()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/_ext/src_numerics.c#L105), so the bug might be somewhere in the latter two.

@ntfrgl, it'd be awesome if you could have a look at this! I wasn't able to trace it back any further as I haven't installed a cython debugger yet, so I was hoping you might find the bug just by staring as you did in [`0ce39ae`](https://github.com/pik-copan/pyunicorn/commit/0ce39ae0c0a7d0e4905c4eb1b96c1c9124b0cc65). :)

If it really is a similar issue, I suppose you'd port those modules to cython as you did in [`b7e546d`](https://github.com/pik-copan/pyunicorn/commit/b7e546d9323a2912af699904f345667caa84934b). Let me know if I should try and do that myself then, but it'd certainly take me a bit more time.

**Comment by fkuehlein** [comment]
#162 looks like it might be related to this issue. The cython/C functions 

[`_cross_correlation_max()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/_ext/numerics.pyx#L50)/[`_cross_correlation_max_fast()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/_ext/src_numerics.c#L45) 

and 

[`_cross_correlation_all()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/_ext/numerics.pyx#L86)/[`_cross_correlation_all_fast()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/funcnet/_ext/src_numerics.c#L80) 

used in `CouplingAnalyis` should therefore be looked into as well.

**Comment by ntfrgl** [comment]
The test suite passes on the freshly installed `master` branch for me, hence I am unable to reproduce this issue at the moment. You might want to look at my recent commits touching these files and see if reverting them changes your situation: 6dc0f63, 402197f, 21b0b6f. For example, if reverting the third commit resolved your issue, then that might indicate a platform-specific problem with the `ALLOCA` macro defined there.

`funcnet/_ext/src_numerics.c::_get_nearest_neighbors_fast()` is the last function in that file which has not been Cythonized yet. It would be great if you could port it, examine the remaining C functions (compare them against the legacy Weave code in the original commits and the current Cython versions), and delete the C file.

**Comment by fkuehlein** [comment]
That's curious. I did a fresh install on a new conda environment and still get the segfaults wenn running the test suite via tox.

I admit my system is not the latest, running on macOS 10.13, not sure if that might be a problem. I still have a conda=23.3 and python=3.10 though.

I could not do full reverts of the above commits because that breaks the cython compilation on reinstall, so I tried reverting only changes concerning `funcnet` (including `setup.py` and `core/_ext/types.{pxd|py}`) for all the above commits:
- 21b0b6f (that's the `ALLOCA` macro) 
- 402197f (except non-mergable revertions in numerics.pyx)
- 6dc0f63

which all compiled fine, but didn't fix the segfault.

I also tried python 3.9 and 3.11 but no difference. (won't install on python=3.8 because numpy=1.25 needs python>=3.9)

Any more ideas at this point? Otherwise I will try porting `funcnet/_ext/src_numerics.c::_get_nearest_neighbors_fast()` to cython and see if that fixes it. 

Thanks for the hint by the way, didn't realize `funcnet/_ext/src_numerics.c::_cross_correlation_{max|all}_fast()` were unused. `_symmetrize_by_absmax_fast()` is also still in there though.

**Comment by ntfrgl** [comment]
This sounds like a bug whose manifestation is compiler/platform-dependent. Cythonizing would therefore probably be of comparable effort to debugging the C version, and reducing the language diversity would be beneficial independently of fixing this bug. Sorry, I overlooked `_symmetrize_by_absmax_fast()`, but the same reasoning applies for it.

I fixed the Numpy issue in a9a70b2.

**Comment by fkuehlein** [comment]
Thanks for fixing the numpy issue! Will look into cythonizing the remaining C functions for `CouplingAnalysis` as soon as possible.
