### ISSUE TITLE
BUG: `CrossRecurrencePlot()` throws TypeError with fixed recurrence rate

### ISSUE THREAD

**Issue by fkuehlein** [pik-copan/pyunicorn#188]
```python

from pyunicorn.core.data import Data
from pyunicorn.timeseries import CrossRecurrencePlot

def create_test_data():
    tdata = Data.SmallTestData().observable()
    tdata -= np.mean(tdata, axis=1)[:, None]
    tdata /= np.sqrt(np.sum(tdata*tdata, axis=1))[:, None]
    return tdata

tdata = create_test_data()
crp = CrossRecurrencePlot(x=tdata, y=tdata, recurrence_rate=0.2)
```

returns

```bash
----> 2 crp = CrossRecurrencePlot(x=tdata, y=tdata, recurrence_rate=0.2)

File [~/Desktop/23_H2_PIK/pyunicorn/src/pyunicorn/timeseries/cross_recurrence_plot.py:112](https://file+.vscode-resource.vscode-cdn.net/Users/fritz/Desktop/23_H2_PIK/code/issues/~/Desktop/23_H2_PIK/pyunicorn/src/pyunicorn/timeseries/cross_recurrence_plot.py:112), in CrossRecurrencePlot.__init__(self, x, y, metric, normalize, sparse_rqa, silence_level, **kwds)
    109 threshold = kwds.get("threshold")
    110 recurrence_rate = kwds.get("recurrence_rate")
--> 112 RecurrencePlot.__init__(
    113     self, np.empty((2, 0)), metric=metric, normalize=normalize,
    114     sparse_rqa=sparse_rqa, threshold=threshold,
    115     recurrence_rate=recurrence_rate, silence_level=silence_level)
    117 self.CR = None
    118 """The cross recurrence matrix."""

File [~/Desktop/23_H2_PIK/pyunicorn/src/pyunicorn/timeseries/recurrence_plot.py:219](https://file+.vscode-resource.vscode-cdn.net/Users/fritz/Desktop/23_H2_PIK/code/issues/~/Desktop/23_H2_PIK/pyunicorn/src/pyunicorn/timeseries/recurrence_plot.py:219), in RecurrencePlot.__init__(self, time_series, metric, normalize, missing_values, sparse_rqa, silence_level, **kwds)
    214     RecurrencePlot.set_fixed_threshold_std(
    215         self, self.threshold_std)
    216 elif recurrence_rate is not None:
    217     #  Calculate the recurrence matrix R using a fixed recurrence
    218     #  rate
--> 219     RecurrencePlot.set_fixed_recurrence_rate(
    220         self, recurrence_rate)
    221 elif self.local_recurrence_rate is not None:
...
--> 651 distance = self.distance_matrix(self.embedding, self.metric)
    653 #  Get number of nodes
    654 n_time = distance.shape[0]

TypeError: CrossRecurrencePlot.distance_matrix() missing 1 required positional argument: 'metric'
```

`RecurrencePlot` itself works fine for both fixed threshold and fixed recurrence rate. 

When `CrossRecurrencePlot` calls [`RecurrencePlot.__init__()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/timeseries/cross_recurrence_plot.py#L112), `self.timeseries`, and thus `self.embedding` is set to `np.empty((2, 0))`. 
In `RecurrencePlot.set_fixed_threshold()` this works fine, in `RecurrencePlot.set_fixed_recurrence_rate()` it doesn't. 

`RecurrencePlot.set_fixed_threshold()` does 
`distance = RecurrencePlot.distance_matrix(self, self.embedding, self.metric)`,  
`RecurrencePlot.set_fixed_recurrence_rate()` does 
`distance = self.distance_matrix(self, self.embedding, self.metric)` 
(which appears more sensual to me, but I'm not a pro and apparently it doesn't work). 

I changed the latter to match the former in the commit below, and it solves the bug, but I'm not sure if that's the right way to do it. 

@ntfrgl, could you have a quick look at that commit quickly and tell me if it makes sense?

If so, I'll can change other such occurrences in `RecurrencePlot.set_fixed_local_recurrence_rate()` and `RecurrencePlot.set_adaptive_neighborhood_size()`. Also, I will add tests to cover all thresholding modes in `RecurrencePlot` and `CrossRecurrencePlot`, which is what I was about to do when I encountered this in the first place.

**Comment by fkuehlein** [comment]
Nevermind my above 'solution', the problem is somewhere else:

`CrossRecurrencePlot` has its own service method [`distance_matrix(x_embedded, y_embedded, metric)`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/timeseries/cross_recurrence_plot.py#L188).

When `RecurrencePlot` calls `self.distance_matrix()`, it will call `CrossRecurrencePlot.distance_matrix()`, which has three arguments instead of 2.

This needs to be disambiguated.

**Comment by ntfrgl** [comment]
`CrossRecurrencePlot.__init__()` should probably call `RecurrencePlot.__init__()` in a way which suppresses the recurrence matrix computation in the base class. In particular, it should use the [`sparse_rqa`](https://github.com/pik-copan/pyunicorn/blob/e5dfcad6f868f163b9802a64921df23d4f55699a/src/pyunicorn/timeseries/recurrence_plot.py#L206C1-L206C27) keyword or some newly chosen one to indicate this mode of operation, and it should not hand over the `threshold` or `recurrence_rate` arguments, which it is responsible for interpreting itself.

Regarding your first attempt above, you might want to revisit the semantics of the ["self" argument in Python](https://realpython.com/python-classes/#instance-methods-with-self).

**Comment by fkuehlein** [comment]
Looking at this case again:

- I fixed the bug the same way I had done before, in `9f2c542` on a new branch. That makes `CrossRecurrencePlot` work with fixed recurrence rate the same way it did with fixed threshold before: It initialises a `RecurrencePlot`, calling `RecurrencePlot.set_fixed_recurrence_rate()`, but then recalculates the recurrence matrix by calling `CrossRecurrencePlot.set_fixed_recurrence_rate()` afterwards. This way both modes work consistently at least, although not very efficiently.

- As you proposed, `sparse_rqa`-mode will cut the double recurrence matrix calculation, but it is "experimental and currently only works for fixed threshold and the supremum metric". And when calling from CRP, even that case throws an IndexError.  
Hence, in `254c837` I introduced an additional keyword argument `overr_recmat` in `RecurrencePlot.__init__()` to skip only the recurrence matrix calculation, and removed the passing of thresholding arguments from CRP. Does that seem alright to you?  
All line distributions work fine this way, except for #166, and except for non-quadratic CRPs, which is another general CRP-issue though. I'll open a separate issue for that one, and add tests for CRP line dists when #166 is resolved.

Still, If I got it right, the idea of proper class inheritance and method overriding would be not having to take care of exactly these cases, right? Although handling two timeseries instead of one seems not such a straightforward inheritance case indeed, you guys had probably thought that through ..

**Comment by ntfrgl** [comment]
I would rename the new argument `overr_recmat` to something more obvious, e.g., `skip_recurrence`. The technical term is *method overloading*, but it might not be immediately clear to a new user which methods are concerned when an *initialisation argument* refers to overloading. Otherwise, your fix follows exactly the strategy I suggested above, and I think that it can be merged.

The design of the class hierarchy predates my involvement in the project. I agree that this class inheritance and other similar ones are conceptually problematic, although that is a very common problem when trying to fit mathematical relations into the restricted modelling capacity of class inheritance, particularly if the mathematical relations themselves have not been well formalised beforehand. For example, I would have chosen the recurrence matrix as the core abstraction here, defined different constructors for it based on the correlation type and discretisation method, and handled the plots as subsequent visualisation methods for recurrence matrices. But then, if I had designed this library, it would not have used the OO paradigm in the first place.

**Comment by fkuehlein** [comment]
Right, I had implemented that just following your suggestion! I will thus rename the argument as you indicated and make a PR.

Thank you also for the insight on the class hierarchy design, it gets more clear to me now the type of compromise had to be found there.
