### ISSUE TITLE
Tests fail with NumPy 1.24.4

### ISSUE THREAD

**Issue by penguinpee** [pik-copan/pyunicorn#189]
It looks like `np.int` has been removed, resulting in a waterfall of `AttributeError: module 'numpy' has no attribute 'int'`:

Here's one example:

```python
____________________ ERROR collecting tests/test_generic.py ____________________
tests/test_generic.py:22: in <module>
    from pyunicorn import core, climate, timeseries, funcnet
pyunicorn/__init__.py:46: in <module>
    from .core import *
pyunicorn/core/__init__.py:43: in <module>
    from .network import Network, NetworkError, nz_coords, cached_const
pyunicorn/core/network.py:51: in <module>
    from ._ext.numerics import _local_cliquishness_4thorder, \
pyunicorn/core/_ext/numerics.pyx:26: in init pyunicorn.core._ext.numerics
    INTTYPE = np.int
/usr/lib64/python3.11/site-packages/numpy/__init__.py:305: in __getattr__
    raise AttributeError(__former_attrs__[attr])
E   AttributeError: module 'numpy' has no attribute 'int'.
E   `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
E   The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E       https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by ntfrgl** [comment]
This issue was resolved in 3dab5bf (April 2022) and subsequent work, and in particular the line raising this error was changed. Hence I suspect that you are using the latest official release `v0.6.1` (June 2019). While we are expecting a new official release later this year, if you would like to use the package now, I recommend installing the current development version from the `master` branch, see https://github.com/pik-copan/pyunicorn#installation.

**Comment by penguinpee** [comment]
I'm looking forward to that release. I tried backporting, but gave up. Package is building successfully now from master. One issue I encountered and which I couldn't quite explain:

https://github.com/pik-copan/pyunicorn/blob/e5dfcad6f868f163b9802a64921df23d4f55699a/setup.cfg#L143-L144

What is `-n auto` supposed to do? Running tests either through `pytest` or `tox` gave me the following error:

```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
```

That happened with pytest 7.1.3, 7.2.2 and 7.3.2. The `--help` info of pytest does indeed not mention a `-n` option. I ended up removing the option. Tests all passed without it.

**Comment by ntfrgl** [comment]
I'm glad to hear that.

This is a [parallelisation option](https://pytest-xdist.readthedocs.io/en/stable/distribution.html) for the `pytest` plugin `pytest-xdist`. The latter is a declared dependency for the appropriate [package extra](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-extras), as documented in the ["Test suite"](https://github.com/pik-copan/pyunicorn#test-suite) section of our README:

https://github.com/pik-copan/pyunicorn/blob/e5dfcad6f868f163b9802a64921df23d4f55699a/setup.cfg#L66-L75

It should also have been installed automatically in the `tox` env, so you might retry after deleting the cache in `.tox/`.
