### ISSUE TITLE
Ghostly memory leak in Network class

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#19]
Resolve memory leak in Network class apparently related to creation of igraph object from pysparse edge list in set_adjacency_matrix method. 

Possibly this could be solved by using up to date igraph version and scipy.sparse instead of pysparse.

----------------------------------------
Originally reported by: Jonathan Donges
Originally created on: 2013-03-14

**Comment by ntfrgl** [comment]
Need to check this again with pysparse removed now.

----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2015-02-04

**Comment by ntfrgl** [comment]
What's the status quo here?

**Comment by ntfrgl** [comment]
Ping @jdonges.

**Comment by jdonges** [comment]
Issue was solved by earlier transition to scipy.sparse for adjacency matrix management.
