### ISSUE TITLE
ModuleNotFoundError from pip install (version 0.6.1)

### ISSUE THREAD

**Issue by kwan-0915** [pik-copan/pyunicorn#221]
Hello. 

I try to install this library with the command: `pip install pyunicorn` and I get the version 0.6.1 

However, when I import the library, I get the error: `ModuleNotFoundError: No module named 'setup'` I check the library folder, I think the `setup.py` file was missing. 

Eventually, I install directly with `pip install git+https://github.com/pik-copan/pyunicorn@master` and I get version 0.7.1, and everything runs smooth. 

I was wondering if the version pull & install from `pip` has a potential bug. Could you please check and confirm? Thank you.

**Comment by fkuehlein** [comment]
Hi @kwan-0915,

thank you for reporting this. Version 0.6.1 has some known issues so in any case I'd recommend you to stick with 0.7.0 or the current development version from this repo. 

Unfortunately we're currently having trouble with uploading the most recent version 0.7.0 to PyPI, but we're working on it. I will leave this issue open until we've managed to get `pip install pyunicorn` running again.

**Comment by fkuehlein** [comment]
Hi again @kwan-0915,

the most recent release version 0.7.0 can now be found on [PyPI](https://pypi.org/project/pyunicorn/) and should be available via `pip install pyunicorn`. I will therefore close this issue. Please re-open it if you still run into problems with the PyPI install!
