### ISSUE TITLE
BUG: Misbehaving static function Network.ErdosRenyi

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#24]
Number of nodes of returned Network object may deviate from prescribed number when the number of links is fixed instead of link probability. This bug (feature?) is on igraph level.

To do: Replace by function contributed by Jan Feldhoff und Stefan Lange.

---

Originally reported by: Jonathan Donges
Originally created on: 2013-03-27

**Comment by jkroenke** [comment]
I was not able to reproduce this error. Is there a minimal example? If the bug was on igraph level maybe it was solved there?

**Comment by jkroenke** [comment]
This bug could not be reproduced and was probably solved in the migration process from python 2 to python 3.
