### ISSUE TITLE
Consolidate get / set functions

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#30]
Remove get... where mainly calculations are performed.

Use get.. prefix only where there is a meaningful set... function associated to it.

----------------------------------------
Originally reported by: Jonathan Donges
Originally created on: 2014-04-16

**Comment by ntfrgl** [comment]
For set functions, use Python concept of properties for simplication: https://docs.python.org/2/library/functions.html#property

----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-06-13

**Comment by ntfrgl** [comment]
Mostly done in commit ee81c57. Needs to be carefully tested.

Only 2 real properties were defined in ``network.py``. A few candidates remain in other modules where there is a ``set_`` function without additional arguments.

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2015-01-14

**Comment by ntfrgl** [comment]
Can this be closed?

**Comment by jdonges** [comment]
Appears to be consolidated for practical purposes and can be closed.
