### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#31]
Consolidate this...

---

Originally reported by: Jonathan Donges
Originally created on: 2014-04-16

**Comment by ntfrgl** [comment]
Compatibility libraries (both MIT Licence):

- [six](https://pythonhosted.org/six/): Python2.5+, maturer
- [pies](https://github.com/timothycrosley/pies): Python2.6+, simpler

I vote for pies. Is there any realistic long-term need to maintain compatibility with Python2.5?

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-05-02

**Comment by ntfrgl** [comment]
[`weave`](https://github.com/scipy/weave/) only works with Python 2.x. Conversion to Cython is therefore obligatory, see issue #34.

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-06-24

**Comment by jdonges** [comment]
Should be solved when conversion from weave to cython is complete. Need to test then extensively.

**Comment by ntfrgl** [comment]
I still expect some more minor problems, mostly with `print` statements, raw strings, slight differences in `numpy` behaviour (e.g. implicit casts int <-> float) and maybe some standard library functions. Regarding my comment from above, if necessary, I would now rather recommend `six`. When the time has come, we can easily add a few lines to `tox.ini` and `.travis.yml` for Python 3 testing.

**Comment by ntfrgl** [comment]
Solved with #107.
