### ISSUE TITLE
[ENH] Weave -> Cython

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#34]
[`scipy.weave`](http://docs.scipy.org/doc/scipy/reference/tutorial/weave.html) is used all over `pyunicorn` to include C code for performance. For small snippets or disconnected bottleneck-solvers this seems quite handy.

But woven C code has reached a formidable portion of the code base and there seems to be potential for consolidation. Though not urgent, having debugging, profiling, tuning, refactoring and extending in mind, I wonder whether decomposing it properly could be better **in the long run**. I see two major options:
- build a small C library and Python extension modules
- switch to [Cython](http://www.cython.org/)

Cython seems to be very well suited for such an endeavor, and on grounds of maintainability and portability the [SciPy Contributing FAQ](http://docs.scipy.org/doc/scipy-dev/reference/hacking.html#faq) says:

> Therefore the basic advice is: use Cython.

Either way, I would have a great learning experience with such a task. What do you think?

---

Originally reported by: ntfrgl
Originally created on: 2014-05-01

**Comment by ntfrgl** [comment]
Cython would be a good solution. We have been thinking about employing it for quite some time. However, other issues like reducing dependencies have much higher priority now.


----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-05-02

**Comment by ntfrgl** [comment]
The following warnings occurring during `weave` compilation seemingly cannot be muted. They are generated by `weave.converters.blitz` which actually uses the deprecated API. The current C code relies on the calling conventions of this type converter.

```
/usr/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
```

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-06-18

**Comment by ntfrgl** [comment]
weave does not work in Python 3.x. Hence, migration to cython or similar is mandatory at some point, before pyunicorn becomes unmaintainable.

----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-06-25

**Comment by ntfrgl** [comment]
I get warnings like:

In file included from /Users/donges/.cache/scipy/python27_compiled/sc_ba2209bc075701193c650cc2b33fccc20.cpp:11:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/array.h:26:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/array-impl.h:37:
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/range.h:120:34: warning: '&&' within '||' [-Wlogical-op-parentheses]
        return ((first_ < last_) && (stride_ == 1) || (first_ == last_));
                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~ ~~
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/range.h:120:34: note: place parentheses around the '&&' expression to silence this warning
        return ((first_ < last_) && (stride_ == 1) || (first_ == last_));
                                 ^
                (                                 )
In file included from /Users/donges/.cache/scipy/python27_compiled/sc_ba2209bc075701193c650cc2b33fccc20.cpp:23:
In file included from /Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/ndarraytypes.h:1761:
/Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
2 warnings generated.
In file included from /Users/donges/.cache/scipy/python27_compiled/sc_ba2209bc075701193c650cc2b33fccc20.cpp:11:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/array.h:26:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/array-impl.h:37:
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/range.h:120:34: warning: '&&' within '||' [-Wlogical-op-parentheses]
        return ((first_ < last_) && (stride_ == 1) || (first_ == last_));
                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~ ~~
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/weave/blitz/blitz/range.h:120:34: note: place parentheses around the '&&' expression to silence this warning
        return ((first_ < last_) && (stride_ == 1) || (first_ == last_));
                                 ^
                (                                 )
In file included from /Users/donges/.cache/scipy/python27_compiled/sc_ba2209bc075701193c650cc2b33fccc20.cpp:23:
In file included from /Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/ndarraytypes.h:1761:
/Library/Python/2.7/site-packages/numpy-1.8.1-py2.7-macosx-10.7-intel.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
2 warnings generated.


----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-06-26

**Comment by ntfrgl** [comment]
Yes, these are exactly the same warnings as I described above, the difference being that `weave` is actively developed while `scipy.weave` is deprecated. Furthermore, these warnings cause errors in `doctest`s with `scipy.weave`, but not with `weave`.

Currently the only thing we can do is keep up to date with `weave` and think about converting to `Cython`.

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-06-26

**Comment by ntfrgl** [comment]
Migration should involve major refactoring, e.g. reducing code duplication (see #50).

**Comment by ntfrgl** [comment]
``core.interacting_networks`` is the first test case, thus some important decisions have to be made:

- [Embed](http://docs.cython.org/src/reference/compilation.html#distributing-cython-modules) generated ``.c`` files in the distribution?
    - **Suggestion:** Ship only ``.pyx`` with source code release (``Cython`` dependency for developers), but include ``.c`` files in PyPI package (no ``Cython`` dependency for users).
- Cythonize whole modules instead of extracting only heavy functions into small Cython modules.
    - **Pro:** No change in global file hierarchy. Possibility for further performance improvements and consistency checks down the road by treating classes as ``Cython`` extensions and statically declaring properties and methods.
    - **Con:** Extracting functions out into separate modules might disburden refactoring/debugging/profiling. ``Cython`` docstrings in ``Sphinx`` work, but not quite as well as with pure Python, e.g. sorting or ``__init__`` documentation are slightly changed and there are no ``[source]`` links.

**Comment by ntfrgl** [comment]
cc2b51035778d8865a39822529be770203a030a6 implements the infrastructure for building and packaging ``Cython`` as well as the first ``Cython``ized module.

The decisions made:
- Embed ``.c`` files in the distribution, as suggested (see [``setup.py``](https://github.com/pik-copan/pyunicorn/blob/cc2b51035778d8865a39822529be770203a030a6/setup.py#L13), [``MANIFEST.in``](https://github.com/pik-copan/pyunicorn/blob/cc2b51035778d8865a39822529be770203a030a6/MANIFEST.in#L9)).
  - No dependency on ``Cython`` for end users.
- Extract only heavy numeric functions into dedicated ``Cython`` modules (a ``numerics.pyx`` for each subpackage).
  - Get better modularity and leaner compilation, retain documentation sanity, style and static code checking for most (non-``Cython``) code. Doctests are configured to work in ``.pyx`` files, too (see [``setup.py``](https://github.com/pik-copan/pyunicorn/blob/cc2b51035778d8865a39822529be770203a030a6/setup.py#L18), [``tests/test_doctests.py``](https://github.com/pik-copan/pyunicorn/blob/cc2b51035778d8865a39822529be770203a030a6/tests/test_doctests.py#L72)).

**Comment by wbarfuss** [comment]
I did

- 1) core
 -    1) Network
 -    2) GeoNetwork
 -    3) Grid
 -    4) Data
- 2) timeseries
 -    1) RecurrencePlot
 -    2) VisibilityGraph
 -    3) Surrogates (partly)
 
left:
- 2) timeseries
 -    3) Surrogates
 -    4) RecurrenceNetwork
 -    5) CrossRecurrencePlot
 -    6) JointRecurrencePlot
 -    7) InterSystemRecurrenceNetwork
 -    8) JointRecurrenceNetwork
- 3) climate
- 4) funcnet

**Comment by ntfrgl** [comment]
Completed by @harmening in PR #89.
