### ISSUE TITLE
New Sphinx Theme

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#39]
The **Sphinxdoc** theme feels quite old. How about the [**Sphinx Bootstrap Theme**](http://ryan-roemer.github.io/sphinx-bootstrap-theme/) for `pyunicorn`'s next version? Found it here: http://docs.writethedocs.org/tools/sphinx-themes/

---

Originally reported by: ntfrgl
Originally created on: 2014-06-13

**Comment by ntfrgl** [comment]
Looks nice! Let's give it a try.

----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-06-13

**Comment by ntfrgl** [comment]
But the theme is hard to get to work using the instructions given in: http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html

----------------------------------------
Original comment by: Jonathan Donges
Original comment on: 2014-06-13

**Comment by jkroenke** [comment]
Solved with commit 4bc2f368d7adb0dede867f45c189a89af926d439
