### ISSUE TITLE
Clean up experimental, deprecated and redundant code

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#40]
Needs to be done before first public release. Some of this code that may be useful at some point should be moved to some kind of plug-in container classes.

---

Originally reported by: Jonathan Donges
Originally created on: 2014-06-17

**Comment by ntfrgl** [comment]
To be removed:

- `core.network.Network`
    - `_get_eigenvector_centrality_slow()`
    - `_get_arenas_betweenness_slow()`
    - `_get_newman_betweenness_badly()`

----------------------------------------
Original comment by: ntfrgl
Original comment on: 2014-06-25

**Comment by ntfrgl** [comment]
Some of these functions could be used as consistency checks in the test suite.

**Comment by fkuehlein** [comment]
The above mentioned methods have been remove from `Network` and many more such cleanups have been made as of [v0.7.0](https://github.com/pik-copan/pyunicorn/tree/v0.7.0). Still, the issue continues to apply.

**Comment by fkuehlein** [comment]
(uncovered) code that might be removable:
- `core.Network`:
  - `Barabasi_Albert()`: non igraph version, do we need it?
  - `Grow_Preferentially{_old}()`: what is the difference between the two? see #229 for bug
  - `do_nsi_pca_clustering()`, `do_nsi_clustering()`, `do_nsi_hamming_clustering()`: experimental
- `core.GeoNetwork`:
  - `shuffled_by_distance_copy()`
  - `nsi_connected_hamming_cluster_tree()`: experimental
  - `boundary()`: experimental
- `utils.Navigator`:
  - full class: already left out of coverage statistics but still, do we still want it?

Note that there are still many more uncovered methods in the package, containing some very low hanging fruits.
