### ISSUE TITLE
Implement edge-weighted and directed measures in InteractingNetworks class

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#47]
Edge-weighted and directed measures for interacting networks / networks of networks are essential for a more subtle and detailed structural analysis of these systems. In a first step, these measures need to be defined mathematically, following the work by:

J.F. Donges, H.C.H. Schultz, N. Marwan, Y. Zou, J. Kurths. “Investigating the topology of interacting networks - Theory and application to coupled climate subnetworks”. In European Physical Journal B: Condensed Matter and Complex Systems, vol. 84 (no. 4) p635-652 (2011) doi:10.1140/epjb/e2011-10795-8

M. Wiedermann, J.F. Donges, J. Heitzig, J. Kurths. “Node-weighted interacting network measures improve the representation of real-world complex systems”. In Europhysics Letters, vol. 102.2, 28007 (2013) doi:10.1209/0295-5075/102/28007

----------------------------------------
Originally reported by: Jonathan Donges
Originally created on: 2014-09-26

**Comment by jdonges** [comment]
Some work is available by Julian from the CosY group at PIK and can be drawn into the code base.

**Comment by wbarfuss** [comment]
#65 draws cross/internal_in/out_degrees measures from Julian into the codebase.
There might be more to use from Julian, what exactly should be discussed with him

**Comment by jdonges** [comment]
#65 implements relevant measures from J. Maluck, R.V. Donner: A network of networks perspective on global trade. PLOS ONE 10(7), e013310 (2015). doi:10.1371/journal.pone.0133310.
