### ISSUE TITLE
Add event synchronization measure

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#48]
Add event synchronization as a measure for climate network construction.

Following the works by Nishant Malik, Niklas Boers et al:

Malik, N., Bookhagen, B., Marwan, N., & Kurths, J. (2012). Analysis of spatial and temporal extreme monsoonal rainfall over South Asia using complex networks. Climate dynamics, 39(3-4), 971-987.

Boers, N., Bookhagen, B., Marwan, N., Kurths, J., & Marengo, J. (2013). Complex networks identify spatial patterns of extreme rainfall events of the South American Monsoon System. Geophysical Research Letters, 40(16), 4386-4392.

----------------------------------------
Originally reported by: Jonathan Donges
Originally created on: 2014-09-26

**Comment by jdonges** [comment]
Now implemented as EventSynchronization class in funcnet module and as EventSynchronizationClimateNetwork in climate module.
