### ISSUE TITLE
Add weighted and directed motif clustering measures from Delphine's EPL paper

### ISSUE THREAD

**Issue by ntfrgl** [pik-copan/pyunicorn#49]
Measures from this paper, add to Network class:

Zemp, D. C., Wiedermann, M., Kurths, J., Rammig, A., & Donges, J. F. (2014). Node-weighted measures for complex networks with directed and weighted edges for studying continental moisture recycling. EPL (Europhysics Letters), 107(5), 58005.
ISO 690	

----------------------------------------
Originally reported by: Jonathan Donges
Originally created on: 2014-10-03

**Comment by jdonges** [comment]
Now implemented in Network class.
