### ISSUE TITLE
rp.recurrence_rate is None

### ISSUE THREAD

**Issue by JonasAbernot** [pik-copan/pyunicorn#60]
```python
import numpy as np
from pyunicorn.timeseries import RecurrencePlot

x = np.random.normal(size=1000)
rp = RecurrencePlot(x, dim=1, tau=1, metric='supremum',  normalize=False, threshold=0.2)
print rp.recurrence_rate
```
returns
```
None
```

**Comment by ntfrgl** [comment]
Which version are you using? I cannot reproduce this behaviour with ``HEAD``.

During initialization, ``RecurrencePlot.supremum_distance_matrix()`` should be calculated, which involves ``weave`` code. Are you experiencing problems with other ``weave`` functions, too? Is there any other output?

**Comment by JonasAbernot** [comment]
Wop,
Sorry, my version was from April, I updated to HEAD, updated netcdf4 and everything works. I don't know what happened.

By the way, thanks you for your work.

**Comment by ntfrgl** [comment]
Nice to hear!
