### ISSUE TITLE
BUG: Dataset transposition in RainfallClimateNetwork is done for observable but not anomaly

### ISSUE THREAD

**Issue by makulatur** [pik-copan/pyunicorn#62]
Hi, thanks for the awesome package!

When you initialize a RainfallClimateNetwork, the ClimateData.data.observable is in the format (time, index). On line 147ff of rainfall.py, the observable is transposed to (index, time) for further processing, but when the rainfall anomalies are calculated from ClimateData.data.anomaly a few lines further down, the original (time, index) is kept. 

This leads to a segmentation fault in the function calculate_corr later on since it expects the anomalies in the (index, time) format. I suspect this has just been overlooked in some code refactoring. 

The easy fix is to change `anomaly = self.calculate_rainfall(self.data.anomaly(), scale_fac, offset)`
 to `anomaly = self.calculate_rainfall(self.data.anomaly().T, scale_fac, offset)` in line 159.

All the best,
Malte

**Comment by ntfrgl** [comment]
Thank for the precise diagnosis! Does the method behave correctly for you now?
