### ISSUE TITLE
[BUG] Error when computing RQA measures in joint_recurrence_network

### ISSUE THREAD

**Issue by marcwie** [pik-copan/pyunicorn#71]
Class raises error when computing, e.g. determinism()

> > > 'JointRecurrenceNetwork' object has no attribute '_diagline_dist_cached'

or when computing trapping_time()

> > > 'JointRecurrenceNetwork' object has no attribute '_vertline_dist_cached'

**Comment by jkroenke** [comment]
This bug could not be reproduced and was probably solved in the migration process from python 2 to python 3.
