### ISSUE TITLE
Wrong error raised when initializing `JointRecurrenceNetwork` with missing parameters

### ISSUE THREAD

**Issue by marcwie** [pik-copan/pyunicorn#72]
When initializing JointRecurrenceNetwork without, e.g., specifying the recurrence_rate the class raises an error:

> > > 'JointRecurrenceNetwork' object has no attribute 'JR'

It would be beneficial to raise an error related to the missing informations provided by the user.

**Comment by fkuehlein** [comment]
This has been resolved as of e1fb60b.
