### ISSUE TITLE
Working with Matplotlib in Virtual environments

### ISSUE THREAD

**Issue by fusaroli** [pik-copan/pyunicorn#79]
As I have Python 3 installed as main python framework, I created a Python 2 virtual environment with Anaconda (on OS X), to be able to run pyunicorn. However, I am getting crashes whenever pylab is necessary (e.g. when trying to visualize recurrence plots), plausibly due to conflicts between matplotlib and virtual environments. Log reported below.

The related support page (http://matplotlib.org/1.5.0/faq/virtualenv_faq.html) suggests that Anaconda environments should not suffer from this issue, but I do get the error. I realize this is not a pyunicorn specific issue, but it might at least be mentioned in the installation instructions.

---

RuntimeError                              Traceback (most recent call last)
<ipython-input-36-4a33226ba71e> in <module>()
----> 1 import pylab
      2 pylab.matshow(rp.recurrence_matrix())
      3 pylab.show()

/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/pylab.py in <module>()
----> 1 from matplotlib.pylab import *
      2 import matplotlib.pylab
      3 **doc** = matplotlib.pylab.**doc**

/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/pylab.py in <module>()
    272 from numpy.linalg import *
    273 
--> 274 from matplotlib.pyplot import *
    275 
    276 # provide the recommended module abbrevs in the pylab namespace

/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/backends/**init**.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = **import**(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py in <module>()
     22 
     23 import matplotlib
---> 24 from matplotlib.backends import _macosx
     25 
     26 

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

**Comment by jdonges** [comment]
Think about mentioning this as a potential issue in the installation instructions.

**Comment by jdonges** [comment]
Can the error be reproduced with command `import matplotlib` in the same environment.
