### ISSUE TITLE
BUG: Error in embedding rountine in RecurrenceNetwork / RecurrencePlot classes

### ISSUE THREAD

**Issue by jdonges** [pik-copan/pyunicorn#83]
This appears to be some bug related to cython. Here is a minimal example:

> In [22]: `x = np.sin(np.linspace(0, 10 * np.pi, 1000))`
> ## In [23]: `rn = RecurrenceNetwork(time_series=x, dim=1, tau=20, recurrence_rate=0.05)`
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-23-846a6130cfc7> in <module>()
> ----> 1 rn = RecurrenceNetwork(time_series=x, dim=1, tau=20, recurrence_rate=0.05)
> 
> /Users/donges/Work/repos/pyunicorn-dev/pyunicorn/pyunicorn/timeseries/recurrence_network.pyc in **init**(self, time_series, metric, normalize, missing_values, silence_level, *_kwds)
>     103                                 normalize=normalize,
>     104                                 missing_values=missing_values,
> --> 105                                 silence_level=silence_level, *_kwds)
>     106 
>     107         #  Set diagonal of R to zero to avoid self-loops in the recurrence
> 
> /Users/donges/Work/repos/pyunicorn-dev/pyunicorn/pyunicorn/timeseries/recurrence_plot.pyc in **init**(self, time_series, metric, normalize, missing_values, sparse_rqa, silence_level, **kwds)
>     156             #  Embed the time series
>     157             self.embedding = self.embed_time_series(self.time_series, self.dim,
> --> 158                                                     self.tau)
>     159             """The embedded time series."""
>     160         else:
> 
> /Users/donges/Work/repos/pyunicorn-dev/pyunicorn/pyunicorn/timeseries/recurrence_plot.pyc in embed_time_series(time_series, dim, tau)
>     422         embedding = np.empty((n_time - (dim - 1) \* tau, dim), dtype="float32")
>     423 
> --> 424         _embed_time_series(n_time, dim, tau, time_series, embedding)
>     425         return embedding
>     426 
> 
> /Users/donges/Work/repos/pyunicorn-dev/pyunicorn/pyunicorn/timeseries/numerics.pyx in pyunicorn.timeseries.numerics._embed_time_series (pyunicorn/timeseries/numerics.c:3091)()
>     174 # recurrence plot==============================================================
>     175 
> --> 176 def _embed_time_series(
>     177     int n_time, int dim, int tau,
>     178     np.ndarray[FLOAT32TYPE_t, ndim=1] time_series,
> 
> ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

It works without embedding:

> In [24]: rn = `RecurrenceNetwork(time_series=x, recurrence_rate=0.05)`
> Calculating recurrence plot at fixed recurrence rate...
> Calculating the supremum distance matrix...

**Comment by wbarfuss** [comment]
checkout
https://github.com/pik-copan/pyunicorn/blob/master/pyunicorn/timeseries/recurrence_plot.py#L140

commenting out the subsequent line solves this problem. But I don't know why it was there in the first place. 

alternatively one can change the `dim` to `2` in 
https://github.com/pik-copan/pyunicorn/blob/master/pyunicorn/timeseries/numerics.pyx#L178

I think the latter would solve the problem once and for all. But it might be that `embed_time_series` is called outside the `__init__` method with a one dimensional `time_series`. That wouldn't be possible anymore. (Of course, one could do the `time_series` reshaping in the `embed_time_series` method.

What are your though?
