### ISSUE TITLE
BUG: set_non_local() does not work for TsonisClimateNetwork

### ISSUE THREAD

**Issue by fmaschler** [pik-copan/pyunicorn#85]
A climate_network seems to leave the initial value of `non_local`untouched regardless of changing it with `set_non_local()`. Here is an example showing that after toggling the attribute the triggered function is the same:

> net = climate.TsonisClimateNetwork(data, threshold=0, winter_only=False, non_local=True)
Generating a Tsonis climate network...
Calculating correlation matrix at zero lag from anomaly values...
Extracting network adjacency matrix removing **local connections**...
Calculating angular great circle distance using Weave...
Extracting network adjacency matrix by thresholding...
Setting area weights according to type surface...
>
> print(net)
Tsonis climate network: 
...
Local connections filtered out: **True**
Use only data points from winter months: False
>
> net.set_non_local(False)
Extracting network adjacency matrix removing **local connections**...
Calculating angular great circle distance using Weave...
Extracting network adjacency matrix by thresholding...
Setting area weights according to type surface...
>
> print(net)
Tsonis climate network: 
...
Local connections filtered out: **True**
Use only data points from winter months: False

The same behaviour is shown for networks initially set to `non_local=False`, just the other way around.
Using the parameter explicily (`net.set_non_local(non_local=True)`) does not help.

**Comment by jkroenke** [comment]
This bug could not be reproduced and was probably solved in the migration process from python 2 to python 3.
