### ISSUE TITLE
ENH: Improve test framework coverage

### ISSUE THREAD

**Issue by jdonges** [pik-copan/pyunicorn#94]
Do this in the course of weave -> cython conversion.

**Comment by jdonges** [comment]
Also add button to doc showing test coverage in percent.

**Comment by fkuehlein** [comment]
This issue can be closed as improving the test coverage is enforced by including CodeCov in the CI workflow as of 3366b60 and reestablishing the CI altogether with #192. The CodeCov badge has been included as of a6362e4.
